import { GetServerSideProps, NextPage } from "next";
import styles from '../styles/Home.module.css'
import Navbar from '../components/Navbar'
import Head from 'next/head'
import Link from "next/link";

interface GuideProps{
  data: {
    id: number
    title: string
    body: string
    tags: string
    user: number
  }[];
}

const guideEndpoint = 'http://127.0.0.1:8000/guide/posts/';

export const getServerSideProps: GetServerSideProps = async () =>  {
  // multipart form
  const res = await fetch(guideEndpoint, { method: 'GET' });
  const data = await res.json();
  return {
    props: {
      data
    }
  }
}

export default function Guide({ data }: GuideProps){
  console.log(data)
  return (
    <div className={styles.container}>
      <Head>
        <title>Borum</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <main className={styles.main}>
        <h1 className={styles.title}>
          Community Guide
        </h1>

        <p className={styles.description}>
          Posts
        </p>

        <ul className={styles.grid}>
          {data.map(({ id, title }) => {
            return (
              <li key={id} className={styles.card}>
                <Link href='/character/[id]' as={`/character/${id}`}>
                  <a>
                    <h2>{title}</h2>
                  </a>
                </Link>
              </li>
            )
          })}
        </ul>

      </main>

      <footer className={styles.footer}>
        <a
          href=""
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by Borum
        </a>
      </footer>
    </div>
  )
}

