import { NextPage } from "next";
import styles from '../styles/Home.module.css'
import Navbar from '../components/Navbar'
import Head from 'next/head'
import { useEffect, useState } from 'react';

const guideEndpoint = 'http://127.0.0.1:8000/guide/posts/';

export async function getServerSideProps() {
  const res = await fetch(guideEndpoint);
  const data = await res.json();
  return {
    props: {
      data
    }
  }
}

const Guide: NextPage = ({ data }) => {
  console.log(data)
  const { info, results: defaultResults = [] } = data;
  const [results, updateResults] = useState(defaultResults);
  const [page, updatePage] = useState({
    ...info,
    current: guideEndpoint
  });
  const { current } = page;

  useEffect(() => {
    if (current === guideEndpoint) return;

    async function request() {
      const res = await fetch(current)
      const nextData = await res.json()

      updatePage({
        current,
        ...nextData.info
      });

      if (!nextData.info?.prev) {
        updateResults(nextData.results);
        return;
      }

      updateResults((prev: any) => {
        return [
          ...prev,
          ...nextData.results
        ]
      })
    }
    request();
  }, [current]);


  return (
    <div className={styles.container}>
      <Head>
        <title>Borum</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <main className={styles.main}>
        <h1 className={styles.title}>
          Community Guide
        </h1>

        <p className={styles.description}>
          Posts
        </p>

        <ul className={styles.grid}>
          {results.map((result: { id: any; title: any; }) => {
            const { id, title } = result;
            return (
              <li key={id} className={styles.card}>
                <a>
                  <h2>{title}</h2>
                </a>
                {/* <Link href='/character/[id]' as={`/character/${id}`}>
                                    <a>
                                        <h2>{title}</h2>
                                    </a>
                                </Link> */}
              </li>
            )
          })}
        </ul>
        <div className={styles.grid}>
          {results.map((result: { id: number; title: string; tags:string; }) => {
            const { id, title, tags } = result;
            return (
              <a href="" key={id} className={styles.card}>
                <h2>{title}</h2>
                <p>{tags}</p>
              </a>
            )
          })}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href=""
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by Borum
        </a>
      </footer>
    </div>
  )
}

export default Guide;