import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Navbar from '../components/Navbar'
import { useEffect, useState } from 'react'

const Home: NextPage = () => {

  const [message, setMessage] = useState('');
  const [auth, setAuth] = useState(false);

  useEffect(() => {
      (
          async () => {
              try {
                  const response = await fetch('http://localhost:8000/users/user', {
                      credentials: 'include',
                  });

                  const content = await response.json();

                  setMessage(`Hi ${content.name}, you're logged!`);
                  setAuth(true);
              } catch (e) {
                  setMessage('You are not logged in');
                  setAuth(false);
              }
          }
      )();
  });

  return (
    <div className={styles.container}>
      <Head>
        <title>Borum - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Navbar auth={auth} />

      <main className={styles.main}>
        <h1 className={styles.title}>
          {message}
        </h1>
      </main>
    </div>
  )
}

export default Home
