import type { NextPage } from "next";
import Head from "next/head";
import { SyntheticEvent, useState } from "react";
import Navbar from "../components/Navbar";
import {useRouter} from "next/router";

type LoginFields = {
  email: string;
  password: string;
};

const Login: NextPage = () => {
  const router = useRouter()
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");

  const submit = async (e:SyntheticEvent) =>{
    e.preventDefault();

    await fetch('http://localhost:8000/users/login', {
      method: 'POST',
      headers: {'Content-Type': 'application/json'},
      credentials: 'include',
      body: JSON.stringify({
        email,
        password
      }) 
    }) 
    await router.push('/')
  }

  return (
    <div>
      <Head>
        <title>Borum - Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <main>
        <h1>Login</h1>
        <form className="flex flex-col gap-2" onSubmit={submit}>
          <input type="text" placeholder="email" required onChange={e => setEmail(e.target.value)} />
          <input type="password" placeholder="password" required onChange={e => setPassword(e.target.value)} />
          <button className="bg-blue-500 text-white p-5" type="submit">Submit</button>
        </form>
      </main>
    </div>
  );
};

export default Login;
