import type { NextPage } from 'next'
import Head from 'next/head'
import Navbar from '../components/Navbar'
import { FieldValues, SubmitHandler, useForm } from 'react-hook-form'

type LoginFields = {
  name: string,
  password: string,
}

const Login: NextPage = () => {
  const {register, handleSubmit } = useForm<LoginFields>();

  const onSubmit = handleSubmit((data) => {
    console.log(data)
  })

  return (
    <div>
      <Head>
        <title>Borum - Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <main>
        <h1>Login</h1>
        <form className='flex flex-col gap-2' onSubmit={onSubmit}>
          <input type="text"      {...register('name')}placeholder='name' />
          <input type="password"  {...register('password')}placeholder='password' />
          <input type="submit" className='bg-blue-500 text-white p-5' value='Login'/>
        </form>
      </main>
    </div>
  )
}

export default Login
