import type { NextPage } from "next";
import Head from "next/head";
import {useRouter} from "next/router";
import { SyntheticEvent, useState } from "react";
import Navbar from "../components/Navbar";

const Login: NextPage = () => {
  const router = useRouter()

  const [name, setName] = useState("");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");

  const submit = async (e: SyntheticEvent) => {
    e.preventDefault();
    await fetch('http://localhost:8000/users/register', {
      method: "POST",
      headers: {'Content-Type': 'application/json'},
      body: JSON.stringify({
        name,
        email,
        password
      })
    });
    await router.push('/login')
  }

  return (
    <div>
      <Head>
        <title>Borum - Register</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <main>
        <h1>Register</h1>
        <form className="flex flex-col gap-2" onSubmit={submit}>
          <input type="text" placeholder="name" required onChange={e => setName(e.target.value)} />
          <input type="email" placeholder="email" onChange={e => setEmail(e.target.value)} />
          <input type="password" placeholder="password" onChange={e => setPassword(e.target.value)} />
          <button className="bg-blue-500 text-white p-5" type="submit">Submit</button>
        </form>
      </main>
    </div>
  );
};

export default Login;
