import { GetServerSideProps, NextPage } from "next";
import styles from '../../styles/Home.module.css'
import Navbar from '../../components/Navbar'
import Head from 'next/head'
import Link from "next/link";

interface GuideProps {
  data: {
    id: number
    title: string
    body: string
    tags: string
    user_id: string
  };
}

const guideEndpoint = 'http://127.0.0.1:8000/guide/posts';

export const getServerSideProps: GetServerSideProps = async (params) => {
  const { id } = params.query;
  const res = await fetch(`${guideEndpoint}/${id}`, { method: 'GET' });
  const data = await res.json();
  return {
    props: {
      data
    }
  }
}

export default function Guide({ data }: GuideProps) {
  return (
    <div className={styles.container}>
      <Head>
        <title>{data.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          {data.title}
        </h1>

        <div className="profile">
          {/* <div className="profile-image">
            <img src={image} alt={name} />
          </div> */}
          <div className="profile-details">
            <ul>
              <li>
                <strong>body:</strong> {data.body}
              </li>
              <li>
                <strong>tags:</strong> {data.tags}
              </li>
              <li>
                <strong>User:</strong> {data.user_id}
              </li>
            </ul>
          </div>
        </div>

        <p>
          <Link href='/guide' className='styles.beck'>
            Back to all GUIDES
          </Link>
        </p>

      </main>
    </div>
  )
}

